#!/bin/bash
ROOT=/var/aos/specs/http_spec
runX kill http_reply
runX --root $ROOT --log ${ROOT}/log.json --log-format json create --bundle ${ROOT} --pid-file ${ROOT}/init.pid http_reply
runX start http_reply
#runX --root /run/containerd/runc/default --log /run/containerd/io.containerd.runtime.v2.task/default/1/log.json --log-format json create --bundle /run/containerd/io.containerd.runtime.v2.task/default/1 --pid-file /run/containerd/io.containerd.runtime.v2.task/default/1/init.pid 1
